### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Garito** [centrifugal/cent#11]
Hi!
Is there any real documentation for this library?

For instance:
generate_api_sign

Thanks!

**Comment by FZambia** [comment]
Hello! Sorry for late reply - was in vacation.

Actually I missed this somehow, will add to README.

**Comment by Garito** [comment]
Thanks!

**Comment by FZambia** [comment]
@Garito just updated README mentioning helper functions from `cent`. Please, check it out.

**Comment by Garito** [comment]
Ouiea! Nice!
Seems to be ok to me
But you know... now my centrifugo is up and running I don't need it anymore hahahahaha!!!

Thanks a lot for the quick fix. I think that the absence of issues will reveal that this one was perfectly covered

Thanks again!!!
