### ISSUE TITLE
How would I go about reading the API constantly?

### ISSUE THREAD

**Issue by Khailz** [centrifugal/cent#13]
I am trying to make a python client that reads the history and gets the latest message in realtime, but only so far have I only been able to do it with the time module. Is there a way I can get the updates in realtime like javascript?

**Comment by FZambia** [comment]
Hi, its not possible as Cent is only HTTP API client. For working with realtime messages you need Centrifugo websocket client (we dont have one). What’s your use case?

**Comment by Khailz** [comment]
I want you use the Centrifugo server to send notifications and messages between the Javascript on the HTTP page and a Python application looking out for the notifications and messages

**Comment by FZambia** [comment]
Do you have a chance to look for notifications and messages in your publisher which generates new messages so you don't need separate Python client?

**Comment by Khailz** [comment]
I don't understand what you mean by publisher but the python client is something entirely different, its a bridge between my website and Teamspeak 3, I am trying to have real time messages between the two.

**Comment by FZambia** [comment]
How you publish new messages to Centrifugo?

In idiomatic case you have `centrifuge-js` that subscribed on channels in Centrifugo. New messages generated by clients come to Centrifugo from your site backend -  you first send new messages via POST AJAX call from web browser to your site backend and then publish messages via HTTP API to Centrifugo (and Centrifugo broadcasts it). I suggest put your bridge logic on your web site backend - as soon you publish message to Centrifugo you can also send message to Teamspeak.

**Comment by Khailz** [comment]
I use centrifuge-js on the website and I'm not familiar with JS or Ajax and
Jquery so I was looking for a way to do it through python, since my site is
built on Django

**Comment by FZambia** [comment]
With Django you anyway can not work with persistent connection out of the box - so you most probably have to do it in separate process.

So you can try to do as I described above - send messages from browser to Django via AJAX and then send to both Centrifugo and Teamspeak.

Actually there is [Python websocket client on top of asyncio](https://github.com/vovadenisov/centrifuge-python) - but this is a work in progress and we don't plan to release it in near future - it works but API will most likely to change and it lacks many features at moment.

**Comment by Khailz** [comment]
I know that I can just send the notifications straight to teamspeak but
that requires the client to keep reconnecting every time to send a
notification when I could just use my already running system to do it
instead

**Comment by FZambia** [comment]
If all messages go through (or from) your site backend - you don't need client to be online.

**Comment by FZambia** [comment]
Maybe I just don't understand what you are trying to achieve so my advices are just wrong:)

**Comment by Khailz** [comment]
I have a script that monitors the TeamSpeak server so having the
notification straight to teamspeak and does other process, doing that on
the website end would just cause requests to take longer. For instance the
site checks who is online on TS but takes a bit longer to load since every
time it checks for the TS information, it has to connect, get the info,
disconnect, then report back and the request will keep you loading a bit
longer. I feel like just asking the script who is online will make it much
faster since it's less steps for the request to go through just to send a
message.

**Comment by FZambia** [comment]
Sorry, I need more details - it's hard to understand your idea reading your description. Let's continue this discussion in our [Gitter chat](https://gitter.im/centrifugal/centrifugo). What you ask in issue is out of scope of this library. But this does not mean that it's not possible to implement in some alternative way which we can find.
