### ISSUE TITLE
Latest version does not work with v1

### ISSUE THREAD

**Issue by orzel89** [centrifugal/cent#15]
Hey, I've just spent few hours trying to figure out why centrifugo throws out "no sign found in API request". Would be nice to create a branch with 2.1.0 version to avoid confusion for new users.

**Comment by FZambia** [comment]
@orzel89 sorry for inconvenience. i've added [compatibility notes](https://github.com/centrifugal/cent#centrifugo-compatibility) to readme. Also created tag for v2.1.0 and v3.0.0

Hope this helps

**Comment by orzel89** [comment]
Great, thank you.
