### ISSUE TITLE
Generate token for client side

### ISSUE THREAD

**Issue by KakarN** [centrifugal/cent#16]
Hi,

I am trying to generate a token for the client side user. I went through the documentation on [generating token and signatures](https://fzambia.gitbooks.io/centrifugal/content/server/tokens_and_signatures.html), and there is a note saying:

> Note that our API clients already have functions to generate client token - you don't have to implement this yourself until you want to implement it for another language for which we don't have API client yet

I am using the latest version of centrifugo (v2.1.0) and cent (v3.0.0), but there is no such functions to generate the token. I have looked on the other cent versions (v2.1.0), and the `generate_token` function and many other functions are available.

Am I missing something on the latest cent version? Could you please help me how to generate token for the client side so that I can connect to the centrifugo server? If it helps, I am using Pythton v3.6.7 and Django v2.1.7.

Thank you

**Comment by FZambia** [comment]
@KakarN hello! you are looking at docs for Centrifugo v1. Actual doc is https://centrifugal.github.io/centrifugo/, see chapter about authentication (https://centrifugal.github.io/centrifugo/server/authentication/) which describes how to generate connection token for Centrifugo v2 using any JWT library.

**Comment by KakarN** [comment]
Aha! Thank you! That helped with the authentication token.

Although I have another problem regarding the token generation on private channel. Please bear with me.

This is the centrifugo config:

```
{
  "secret": "05760ffb-443f-4ad2-a515-ffe35a97b273",
  "admin": true,
  "admin_password": "50e28789-3683-40f1-80aa-e70942613220",
  "admin_secret": "a448ba37-2440-47eb-9c13-233f24fccc2c",
  "api_key": "0fc02493-769c-4971-a1e4-25352cde046c",
  "anonymous": true,
  "publish": true,
  "presence": true,
  "join_leave": true,
  "history_size": 10,
  "history_lifetime": 30,
  "debug": true
}
```

On the client side when I get the auth token and I pass it to the Centrifuge as the token. I have also provided `refreshEndpoint` and `subscribeEndpoint` to get auth token and subscribe token on the client side. I can subscribe to public channel with the auth token without any issue. But, when I try to subscribe to a private token, I can see on the django server log that the `subscribeEndpoint` is called, but I get an error: 

> message permission denied

Client side js:

```
const WebSocketURL = "ws://192.168.33.10:8000/connection/websocket"
const SockjsURL = "http://192.168.33.10:8000/connection/sockjs"
const URL = SockjsURL
const centrifuge = new Centrifuge(URL, {
  debug: true,
  refreshEndpoint: 'http://192.168.33.10/refresh-centrifugo-token/',
  subscribeEndpoint: 'http://192.168.33.10/private-centrifugo-token/'
});

// from the django server
centrifuge.setToken(token)


var callbacks = {
  "publish": function(message) {
    // See below description of message format
    console.log('on publish', message);
  },
  "join": function(message) {
    // See below description of join message format
    console.log('on join', message);
  },
  "leave": function(message) {
    // See below description of leave message format
    console.log('on leave', message);
  },
  "subscribe": function(context) {
    // See below description of subscribe callback context format
    console.log('on subscribe', context);
  },
  "error": function(errContext) {
    // See below description of subscribe error callback context format
    console.log('on error', errContext);
  },
  "unsubscribe": function(context) {
    // See below description of unsubscribe event callback context format
    console.log('on unsubscribe', context);
  }
}

// const ChannelName = "news"
const ChannelName = "$private"

var subscription = centrifuge.subscribe(ChannelName, callbacks);

centrifuge.on('connect', function(context) {
  console.log('context', context)
});

centrifuge.connect();
```

As mentioned above, I have setup two end points on the django server to refresh the auth token, and to generate token for the private channel.

```
@csrf_exempt
def get_auth_token(request):
    if not request.is_ajax() or not request.method == "POST":
        raise Http404
    data = {
        'token': generate_auth_token()
    }
    return JsonResponse(data)


@csrf_exempt
def get_private_token(request):
    if not request.is_ajax() or not request.method == "POST":
        raise Http404
    data = json.loads(request.body)
    client = data.get('client')
    channels = data.get('channels')
    channel1 = channels[0]
    data = {
        'token': generate_private_token(client, channel1)
    }
    return JsonResponse(data)


def generate_auth_token():
    token = jwt.encode({"sub": "42", "exp": int(time.time()) + 1 * 60, "info": {"name": "Alexander Emelin"}}, secret,
                       algorithm="HS256").decode()
    return token


def generate_private_token(client, channel):
    token = jwt.encode({"client": client, "channel": channel}, secret, algorithm="HS256").decode()

    return token
```

I can see the on django server logs, that the `subscribeEndpoint` is called. But I am not sure why I cannot subscribe with the private token. Could you please help me where I am missing something here?

**Comment by KakarN** [comment]
Aha! Thank you!

**Comment by FZambia** [comment]
See example on how to generate subscription token [in Tornado example](https://github.com/centrifugal/examples/blob/master/tornado_application/main.py#L79), also [centrifuge-js docs](https://github.com/centrifugal/centrifuge-js#private-channels-subscription) about format expected.

**Comment by KakarN** [comment]
Yes! I ended up doing it this way:

```
@csrf_exempt
def get_private_token(request):
    if not request.is_ajax() or not request.method == "POST":
        raise Http404
    data = json.loads(request.body)
    client = data.get('client')
    channels = data.get('channels')
    token_list = []

    for channel in channels:
        channel_data = {
            "channel": channel,
            "token": generate_private_token(client, channel)
        }
        token_list.append(channel_data)

    response_data = {
        "channels": token_list
    }
    return JsonResponse(response_data)


def generate_private_token(client, channel):
    token = jwt.encode({"client": client, "channel": channel}, secret, algorithm="HS256").decode()
    print(channel, 'private token', token)
    return token
```

Thank you so much for your help!

**Comment by KakarN** [comment]
@FZambia Hi! I just wanted to point out how I was reading the old version's documentation. On the **[High-level library API](https://github.com/centrifugal/cent#high-level-library-api)** section, the URL link to check out the available API methods in the readme points to the [old version documentation](https://fzambia.gitbooks.io/centrifugal/content/server/api.html), and not the [new version](https://centrifugal.github.io/centrifugo/server/api/).

**Comment by FZambia** [comment]
@KakarN thanks, fixed!
