### ISSUE TITLE
publish data with datetime or Decimal

### ISSUE THREAD

**Issue by flc** [centrifugal/cent#2]
hi, currently client.send() fails if you try to publish data that contains datetime or Decimal objects in https://github.com/centrifugal/cent/blob/master/cent/core.py#L62

It would be great if one could specify a custom JSONEncoder to use somehow (for example the DjangoJSONEncoder if you happen to use django). What I'm trying to do is to publish my serialized django model object into a channel. Or do you think it's a bad idea?

btw thanks for the great work on centrifuge!

**Comment by flc** [comment]
Now that I'm thinking about this what I could do is to create the json string with whatever encoder I want to use and publish that into the channel and handle the deserialization of the json string on client side.

**Comment by FZambia** [comment]
Hello! I think this is a good idea! Just added support for this using `json_encoder` keyword argument for `Client` class - could you check it (its already on Pypi)?

**Comment by flc** [comment]
it would make sense to add the `json_encoder` kwarg to the adjacent Client as well and pass it to the cent client (RawClient).

**Comment by flc** [comment]
and for the adjacent Client use DjangoJSONEncoder as a default? I'm not sure about that.

**Comment by FZambia** [comment]
yes, I will add it to adjacent but wont make DjangoJSONEncoder default.

**Comment by flc** [comment]
thanks!

**Comment by FZambia** [comment]
I am closing this then, please, feel free to reopen or create issues with other questions/bugs/suggestions etc
