### ISSUE TITLE
is this client still receiving updates?

### ISSUE THREAD

**Issue by aryan340** [centrifugal/cent#21]
I am planning to use centrifugo as a service for a new channel layer, adding onto [django channels](https://github.com/django/channels). I would like to know if this project still receives updates so that I can rely on it.

Thanks a lot!

**Comment by FZambia** [comment]
@aryan340 hello, yes - this is still an actual and maintained repo, just no issues and API changes for a long time.

**Comment by FZambia** [comment]
Please share if you will be able to make Centrifugo a channels layer, this would be really interesting.

**Comment by aryan340** [comment]
Sure! There's already a redis channel layer shipped by django, but group sending is slow- there is an active issue regarding that and it is yet to be solved.

As centrifugo scales, it would be a great service for a channel layer. I'll let you know when I start implementing.

**Comment by aryan340** [comment]
@FZambia but there is an issue.
In order to support centrifugo as a service we need server-side subscriptions to effectively subscribe clients from the backend. However, according to the documentation, this feature is only supported by the js client.
![image](https://user-images.githubusercontent.com/69184573/116047139-6632b500-a691-11eb-8968-e5eb3ea36eea.png)

any plans on implementing this soon?

**Comment by FZambia** [comment]
No, there are no plans to implement this since Centrifugo has no such API.

**Comment by aryan340** [comment]
sorry for the miscommunication, I get it now.

**Comment by FZambia** [comment]
@aryan340 feel free to reach out in our community channels if you have more questions, as I said integration with Django channels would be super interesting. Though Centrifugo itself was designed to work well with frameworks like Django out of the box - so in general you can use Django with Centrifugo without implementing channel layer (i.e. not using Django Channels at all).

**Comment by aryan340** [comment]
Great! Thanks a lot! I just realized that.
Closing this. 👍
