### ISSUE TITLE
Get offset instead of publications for offset field in history response

### ISSUE THREAD

**Issue by v1lev** [centrifugal/cent#24]
Hello! Minor issue:
https://github.com/centrifugal/cent/blob/9c1fee78df02730fdb5f44e946a2383cfab2a672/cent/core.py#L264

Both fields are mapped to "publications", the second one should be offset

**Comment by FZambia** [comment]
🤦 

Thanks, @v1lev !

**Comment by FZambia** [comment]
Just fixed this in [v4.1.0](https://github.com/centrifugal/cent/releases/tag/v4.1.0)
