### ISSUE TITLE
Poll the server for number of clients

### ISSUE THREAD

**Issue by thinkwelltwd** [centrifugal/cent#6]
I'm deploying centrifugo in a Django project and I need to manage a process if there are no more clients connected to centrifugo. It doesn't seem to me that cent supports this. Is there a way to find out (from python) how many clients are connected to centrifugo? 

Or if you have some other recommendation, let me know. Thanks!

**Comment by FZambia** [comment]
Hello, yes, Cent does not support this. There is an endpoint `/info/` that web interface uses to get current server stats including how many clients total connected but it's not exposed to HTTP API. Could you  explain a little more detailed why you need this?

**Comment by thinkwelltwd** [comment]
I have a process that sends logging info to the browser via websockets. The process is launched via supervisor in the Django View if it's not already running. But when all clients have left the channel, then I'd like to kill the process. But I only want to do it when I can be sure that there are no users left in the channel (except for the client that's publishing the logs, of course).

So that's what I had in mind.

**Comment by FZambia** [comment]
So it seems like `presence` data for channel then?

**Comment by thinkwelltwd** [comment]
Yes, that's right. If there'd be an easy way to get that, it would just make my day.

**Comment by FZambia** [comment]
https://github.com/centrifugal/adjacent/blob/master/adjacent/client.py#L36

or just:

```python
client.add('presence', {
    'channel': 'your_channel'
})
result, error = client.send()
```

**Comment by FZambia** [comment]
I also want to add `publish`, `history`, `presence` methods directly to `Client` class in `cent` like in `adjacent` client, will make it as soon as I get time for it.

**Comment by thinkwelltwd** [comment]
I might be misunderstanding you. I need the count of clients present in a channel. Doesn't the `presence` method just add a client?

**Comment by FZambia** [comment]
`presence` returns a dictionary with all clients currently subscribed on this channel.

**Comment by thinkwelltwd** [comment]
Enlightenment! I must have had my `presence` settings incorrect. I'm now getting a dict with clients. Thanks so much for your assistance and this excellent project.

**Comment by FZambia** [comment]
You are welcome! I just pushed some new methods to `commands` branch in this repo, there is new methods to simplify sending API commands, will test a little all changes during this week and will release new version with them.

**Comment by thinkwelltwd** [comment]
I reviewed your code changes a bit; looks like some nice improvements. l'll watch for your updates.

**Comment by FZambia** [comment]
v0.5.0 released!
